### ISSUE TITLE
Pickling ngboost models fail

### ISSUE THREAD

**Issue by Ycallaer** [stanfordmlgroup/ngboost#88] opened 2020-02-13 11:52 UTC
Hi,
I am running the latest version of ngboost.
When trying to pickle a ngboost model I get the following failure:
`Can't pickle <class 'ngboost.manifold.Manifold'>: it's not found as ngboost.manifold.Manifold`

The reason for this is that the class is Manifold is nested and pickle doesn't really like that.
Joblib also fails (because it is using pickle in the backend). The only alternative I am currently left with is storing the data of the model as JSON file but this is a bit cumbersome.

Would it be possible to refactor the code so pickle is supported ? Or suggest an alternative way to save models ?

Thanks.

Full code example:
`bs = BootStrapModel(base, n_models=model_parameters['n_models'], n_estimators=model_parameters['n_estimators'])
bs.fit_parallel(X_train, y_train, n_jobs=2, verbose=51)
with open('result.pkl','w') as finalFile:
    pickle.dump(bs, finalFile)
`

**Comment by alejandroschuler** [comment] 2020-02-13 19:03
@Ycallaer this is very interesting! We did not consider pickling or model saving when we wrote the code so I'm glad you are bringing it up so we can address that.

The way the code is set up right now allows for maximum modularity. That's extremely important both for maintainability and making it easy for developers to add new distributions, scores, or 'modes' of regression (e.g. interval censoring). Given that, I don't think we can do a refactor that would let pickling work out-of-the-box. 

However, I'll certainly look into how we can make this work, either with some pickling methods or custom code. I am 100% certain it is possible because at the end of the day saving the parameter-specific boosting models is all that needs to be done to get predictions, and those can certainly be pickled. I'll poke around in the next few days and see what I can do.

**Comment by alejandroschuler** [comment] 2020-02-13 19:38
well that was easier than I thought! https://github.com/stanfordmlgroup/ngboost/commit/3d8dbcd28f233e5ca32fb9487fc1fe555a09c0c2

I'll close this for now but lmk if you have any issues. I've added an example at the end of the vignette too.

**Closed by alejandroschuler** 2020-02-13 19:38 UTC
