### ISSUE TITLE
can you provide a classification example?

### ISSUE THREAD

**Issue by carrielui** [stanfordmlgroup/ngboost#12] opened 2019-10-24 16:41 UTC
I would be nice to have an example of classification problem.

**Comment by avati** [comment] 2019-10-24 16:59
Hi @carrielui, thank you for filing the request. Currently our focus has been on regression problems (since the project started under a research problem that involved probabilistic regression), though the framework could trivially be extended to classification.

What needs to be done is: implement a new ``ngboost.distn.Bernoulli`` or ``ngboost.distn.Categorical`` for binary and multi-class respectively, and classification should just work without any other changes.

Separately, we also welcome community contributions, and happy to help / guide someone to do this if it is required sooner than me getting to it.

**Comment by avati** [comment] 2019-10-25 15:49
Great, will look forward for the PR @wptmdoorn!

**Comment by wptmdoorn** [comment] 2019-10-31 12:33
@romanvoyt I've been busy quite a lot but I expect to upload a first version of the Bernoulli class tonight (in about ~7-9 hours). I would be more than grateful if you would jump in on the project :) I guess ngboost.distns.Bernoulli and Categorical share a lot of common theory and implementation so I think it shouldn't hurt to implement them both.

**Comment by wptmdoorn** [comment] 2019-10-31 21:55
@alejandroschuler I would be willing to do this, but I have to admit I am fairly new to open-source projects and also the amount of math/statistics involved in this project is a lot for me, personally. Once the Bernoulli class is implemented I could give it a go (but there also might be better persons to write such a guide!)

@romanvoyt I just submitted an issue #17, giving it a first try, any help would be really welcome.

**Comment by romanvoyt** [comment] 2019-11-01 04:33
@wptmdoorn Great. Let me check this one later, I hope I can help with it.

**Comment by tonyduan** [comment] 2019-11-23 02:57
Closing this issue out since we now have a classification example.

**Closed by tonyduan** 2019-11-23 02:57 UTC
Labels: enhancement
