### ISSUE TITLE
Very wide prediction intervals with exponential distribution

### ISSUE THREAD

**Issue by albertotonon** [stanfordmlgroup/ngboost#205] opened 2020-11-10 16:11 UTC
Thanks a lot to all devs for making this very useful library available to everyone.

I'm considering using this lib in my job to predict the car market values to be able to provide users with a range instead of a point estimation of the value of their car.

By cross-validating I found that using the exponential distribution gives best results (with a large margin), also, using the normal distribution sometimes made training not converge. The problem I'm facing is that, using such distribution, the 95% confidence intervals are very large, for example
```
>>> exp = stats.expon(scale=10000)
>>> exp.interval(0.95)
(253.17807984289897, 36888.79454113935)
```
Basically, in my case the predictions are ok but the intervals are really not usable.
Is there anything I could do?

**Comment by alejandroschuler** [comment] 2020-11-10 17:58
(duplicate of  #206)

**Closed by alejandroschuler** 2020-11-10 17:58 UTC

**Comment by albertotonon** [comment] 2020-11-11 07:31
Sorry for duplicating: i think i had an issue with the browser when I created the issue and I didn't notice the issue was actually created.
